[[redirects]]
  from = "/missed-call-text-back"
  to = "https://trades.strohmpartners.com"
  status = 301

[[redirects]]
  from = "/admin-services"
  to = "https://admin.strohmpartners.com"
  status = 301
